<a href="https://colab.research.google.com/github/JakeOh/20230228_itwill_java140_lab_python/blob/main/py19_yob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 패키지 임포트

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 데이터셋 준비

*  YOB: Year of Birth
*  github: https://github.com/wesm/pydata-book/tree/3rd-edition/datasets/babynames
*  1880년 ~ 2010년까지 연도별로 텍스트(txt) 파일이 저장되어 있음.
*  각 파일에는 '이름,성별,신생아수'가 comma(,)로 구분되어 있음.
*  (주의) 컬럼 이름은 파일에 없음.

In [2]:
file_path = 'https://github.com/wesm/pydata-book/raw/3rd-edition/datasets/babynames/yob1880.txt'

In [3]:
yob1880 = pd.read_csv(file_path)

In [4]:
yob1880.head()

        Mary  F  7065
0       Anna  F  2604
1       Emma  F  2003
2  Elizabeth  F  1939
3     Minnie  F  1746
4   Margaret  F  1578

`pd.read_csv()` 함수는 파일의 첫번째 줄을 데이터프레임의 컬럼 이름으로 취급함.

CSV 파일에서 컬럼 이름이 포함되어 있지 않은 경우(파일의 첫번째 줄부터 데이터가 시작되는 경우)에는 컬럼 이름들을 함수 호출할 때 `names` 파라미터에 아규먼트로 전달해야 함.

In [5]:
col_names = ['name', 'gender', 'births']  # 데이터프레임 컬럼 이름 리스트

In [6]:
yob1880 = pd.read_csv(file_path, names=col_names)

In [7]:
yob1880.head()

        name gender  births
0       Mary      F    7065
1       Anna      F    2604
2       Emma      F    2003
3  Elizabeth      F    1939
4     Minnie      F    1746

1880년 ~ 2010년까지 각각의 txt 파일들을 읽어서 만들어진 연도별 데이터프레임들을 저장하는 리스트를 만드세요. (결과) 131개의 데이터프레임을 저장하는 리스트.

각각의 데이터 프레임에는 year 컬럼을 추가하세요.